name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      matrix:
        pair:
          - otp-version: '24.3'
            elixir-version: '1.13'
          - otp-version: '24.3'
            elixir-version: '1.14'
          - otp-version: '25.1'
            elixir-version: '1.13'
          - otp-version: '25.1'
            elixir-version: '1.14'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: ./
      with:
        otp-version: ${{matrix.pair.otp-version}}
        elixir-version: ${{matrix.pair.elixir-version}}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
